<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <AssemblyName>DesignPatternSamples.Domain</AssemblyName>
    <RootNamespace>DesignPatternSamples.Domain</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Repository\" />
  </ItemGroup>

</Project>
